sudo: required
services:
        - docker

before_install:
        - docker build -t rado/react-test -f ./client/Dockerfile.dev ./client

script:
        - docker run -e CI=true rado/react-test npm test -- --coverage

after_success:
        - docker build -t rado/multi-client ./client
        - docker build -t rado/multi-nginx ./nginx
        - docker build -t rado/multi-worker ./worker
        - docker build -t rado/multi-server ./server
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
        - docker push rado/multi-client
        - docker push rado/multi-nginx
        - docker push rado/multi-worker
        - docker push rado/multi-server

